name: update server

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed
  workflow_dispatch:
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy docker container with latest image on testnet instance
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOMAIN }}
        username: root
        key: ${{ secrets.SSH_SECRET }}
        port: 22
        script: |
          docker pull threefolddev/owncloud_deployer -a
          tag="$( docker images | awk '{print $2}' | awk 'NR==2{print $1}' )"
          volume="$(docker inspect owncloud | grep volumes | sed 's:/[^/]*$::' | sed 's:.*/::')"
          docker rm -f owncloud
          docker run -ti -d --name owncloud -v "$(volume):/data" -e domain=${{ secrets.DOMAIN }} -e email_host=${{ secrets.EMAIL_HOST }} -e email_port=${{ secrets.EMAIL_PORT }} -e email_username=${{ secrets.EMAIL_USERNAME }} -e email_password=${{ secrets.EMAIL_PASSWORD }} -e mnemonics=${{ secrets.MNEMONICS }} -e chain_url=${{ secrets.CHAIN_URL }} -e network=${{ secrets.NETWORK }} -e admins=${{ secrets.ADMINS }} -e alert_email=${{ secrets.ALERT_EMAIL }} -e support_public_ssh_key=${{ secrets.SUPPORT_PUBLIC_SSH_KEY }} -e restic_repository=${{ secrets.RESTIC_REPOSITORY }} -e restic_password=${{ secrets.RESTIC_REPOSITORY }} -e aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} -e aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}  -e letsencryptemail=${{ secrets.LETSENCRYPTEMAIL }} -p 80:80 -p 443:443 threefolddev/owncloud_deployer:$(tag)
